name: CompatNoCheatPlus
main: me.asofold.bpl.cncp.CompatNoCheatPlus
version: ${project.version}-b${BUILD_NUMBER}
dev-url: 'http://dev.bukkit.org/server-mods/compatnocheatplus-cncp/'

loadbefore:
- NoCheatPlus
softdepend:
- mcMMO
- Citizens
- MagicSpells

commands:
  compatnocheatplus:
    description: 'Manage cncp, currently only showing some info is available.'
    usage: '/<command>'
    permission: 'cncp.cmd.info'
    aliases:
    - cncp